using UnityEngine;
using System.Collections;
namespace Util
{
    public class GridLayoutHeightSetter : MonoBehaviour
    {
        public bool onlyUseActive;
        float o;
        // Use this for initialization
        void Start()
        {
            o = ((RectTransform)transform).sizeDelta.y;
        }

        void Update()
        {
            if (GetComponent<UnityEngine.UI.GridLayoutGroup>().preferredHeight > o)
                ((RectTransform)transform).sizeDelta = new Vector2(((RectTransform)transform).sizeDelta.x, GetComponent<UnityEngine.UI.GridLayoutGroup>().preferredHeight);
        }
    }
}